# Generated by Django 2.0.3 on 2018-05-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180527_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.CharField(choices=[('dispathcer', 'DISPATCHER'), ('operator', 'OPERATOR'), ('warranty', 'WARRANTY'), ('admin', 'ADMIN')], default='operator', max_length=15),
        ),
    ]
