# Generated by Django 2.0.2 on 2018-05-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180528_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(choices=[('dispatcher', 'DISPATCHER'), ('operator', 'OPERATOR'), ('warranty', 'WARRANTY'), ('parts', 'PARTS'), ('admin', 'ADMIN')], default='operator', max_length=15),
        ),
    ]
