# Generated by Django 2.0.3 on 2018-06-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180529_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(choices=[('dispatcher', 'DISPATCHER'), ('operator', 'OPERATOR'), ('warranty', 'WARRANTY'), ('parts', 'PARTS'), ('adminop', 'ADMIN_OP'), ('admindp', 'ADMIN_DP'), ('admin', 'ADMIN')], default='operator', max_length=15),
        ),
    ]
