# Generated by Django 2.0.6 on 2018-06-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180610_0234'),
        ('users', '0007_auto_20180611_1051'),
    ]

    operations = [
    ]
