# Generated by Django 2.0.6 on 2018-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20180611_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(choices=[('dispatcher', 'DISPATCHER'), ('operator', 'OPERATOR'), ('warranty', 'WARRANTY'), ('parts', 'PARTS'), ('adminop', 'ADMIN_OP'), ('admindp', 'ADMIN_DP'), ('admin', 'ADMIN'), ('account', 'ACCOUNT')], default='operator', max_length=15),
        ),
    ]
