# Generated by Django 2.0.3 on 2018-09-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_users_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('change_user_status', 'Can change the status of dispatchers'),)},
        ),
    ]
