# Generated by Django 2.0.3 on 2018-06-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('description_eng', models.CharField(max_length=90)),
                ('description_chn', models.CharField(max_length=100)),
                ('inventory', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('description_eng', models.CharField(max_length=90)),
                ('description_chn', models.CharField(max_length=100)),
                ('parts', models.ManyToManyField(to='units.Part')),
            ],
            options={
                'ordering': ('model',),
            },
        ),
    ]
