# Generated by Django 2.0.6 on 2018-08-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name_eng', models.CharField(max_length=90)),
                ('name_chn', models.CharField(max_length=100)),
                ('description', models.CharField(default='part', max_length=100)),
                ('inventory', models.IntegerField(default=0)),
                ('price_fob', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('price_list', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_enduser', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_dealer', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_partstown', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('name_eng', models.CharField(max_length=90, null=True)),
                ('name_chn', models.CharField(max_length=100, null=True)),
                ('dimension', models.CharField(max_length=100, null=True)),
                ('spec', models.CharField(max_length=100, null=True)),
                ('parts', models.ManyToManyField(null=True, to='units.Part')),
            ],
            options={
                'ordering': ('model',),
            },
        ),
    ]
