# Generated by Django 2.0.6 on 2018-11-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='after_market_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
