# Generated by Django 2.0.6 on 2018-11-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20181102_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='after_market_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
