# Generated by Django 2.0.6 on 2018-06-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20180624_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='description_chn',
            new_name='name_chn',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='description_eng',
            new_name='name_eng',
        ),
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.CharField(default='part', max_length=100),
        ),
    ]
