# Generated by Django 2.0.6 on 2018-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20180625_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='description_chn',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='description_eng',
        ),
        migrations.AddField(
            model_name='unit',
            name='dimension',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_chn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_eng',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='spec',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parts',
            field=models.ManyToManyField(null=True, to='units.Part'),
        ),
    ]
