# Generated by Django 2.0.6 on 2018-12-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20181106_1122'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='PO2China',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('status', models.IntegerField(default=0)),
        #         ('qty', models.IntegerField(default=10)),
        #         ('branch', models.CharField(choices=[('Brea', 'HQ, Brea, CA'), ('Hayward', 'Hayward, CA'), ('Dallas', 'Dallas, TX'), ('Houston', 'Houston, TX'), ('Washington', 'Kent, WA'), ('Colorado', 'Aurora, CO'), ('Florida', 'Tampa, FL'), ('Illinois', 'Homer Glen, IL'), ('Georgia', 'Doraville, GA'), ('New Jersey', 'Fairfield, NJ'), ('Massachusetts', 'Westborough, MA'), ('Ohio', 'Groveport, OH')], max_length=50)),
        #         ('created_time', models.DateTimeField(auto_now_add=True)),
        #         ('ordered_time', models.DateTimeField(blank=True, null=True)),
        #         ('shipped_time', models.DateTimeField(blank=True, null=True)),
        #         ('received_time', models.DateTimeField(blank=True, null=True)),
        #     ],
        # ),
        migrations.AlterField(
            model_name='unit',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name_chn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parts',
            field=models.ManyToManyField(blank=True, null=True, to='units.Part'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # migrations.AddField(
        #     model_name='po2china',
        #     name='part',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Part'),
        # ),
    ]
