# Generated by Django 2.0.3 on 2018-05-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partsinv',
            fields=[
                ('item', models.CharField(blank=True, db_column='Item', max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('group_id', models.CharField(blank=True, db_column='Group_ID', max_length=100, null=True)),
                ('class_id', models.CharField(blank=True, db_column='Class_ID', max_length=100, null=True)),
                ('inventory', models.IntegerField(blank=True, db_column='Inventory', null=True)),
                ('low_inv', models.IntegerField(blank=True)),
                ('high_inv', models.IntegerField(blank=True)),
                ('location', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'partsinv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKSID', models.CharField(max_length=30)),
                ('serialNumber', models.CharField(max_length=50)),
                ('businessName', models.CharField(max_length=100)),
                ('tech', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('shippingMethod', models.CharField(blank=True, choices=[('NDA', 'NEXT DAY AIR'), ('2NDA', 'SECOND DAY AIR'), ('GROUND', 'GROUND')], max_length=20)),
                ('partQty', models.IntegerField()),
                ('requestTime', models.DateField(auto_now_add=True)),
                ('requestStatue', models.NullBooleanField()),
                ('tracking', models.CharField(max_length=50)),
            ],
        ),
    ]
