# Generated by Django 2.0.3 on 2018-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20180524_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='warranty',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
