# Generated by Django 2.0.3 on 2018-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20180526_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='warranty',
            field=models.NullBooleanField(),
        ),
    ]
