# Generated by Django 2.0.3 on 2018-05-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20180526_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='warrantyNote',
            field=models.CharField(default='nonnnnn', max_length=100),
            preserve_default=False,
        ),
    ]
