# Generated by Django 2.0.3 on 2018-05-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_unitbasicinfo_warrantynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='areaCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitbasicinfo',
            name='reciever',
            field=models.CharField(default='Anna', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitbasicinfo',
            name='techNote',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='location_add2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='warrantyNote',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
