# Generated by Django 2.0.3 on 2018-05-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20180526_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='sksid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='warrantyNote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
