# Generated by Django 2.0.3 on 2018-05-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20180527_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
