# Generated by Django 2.0.2 on 2018-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_auto_20180528_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='pre_diagnosis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tsq',
            field=models.TextField(null=True),
        ),
    ]
