# Generated by Django 2.0.2 on 2018-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_auto_20180529_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sksid', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('shipping_method', models.CharField(blank=True, choices=[('NDA', 'NEXT DAY AIR'), ('2NDA', 'SECOND DAY AIR'), ('GROUND', 'GROUND')], max_length=20)),
                ('qty', models.IntegerField()),
                ('request_time', models.DateField(auto_now_add=True)),
                ('tracking', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('location_add1', models.CharField(max_length=200)),
                ('location_add2', models.CharField(max_length=200, null=True)),
                ('location_city', models.CharField(max_length=20)),
                ('location_state', models.CharField(max_length=30)),
                ('location_zip', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
