# Generated by Django 2.0.6 on 2018-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_timerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='techNote',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='warrantyNote',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
