# Generated by Django 2.0.6 on 2018-06-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_auto_20180611_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='followup_customer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitbasicinfo',
            name='followup_customer_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='unitbasicinfo',
            name='followup_tech',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitbasicinfo',
            name='followup_tech_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
