# Generated by Django 2.0.6 on 2018-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_auto_20180611_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='followup_customer_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='followup_tech_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
