# Generated by Django 2.0.6 on 2018-06-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_auto_20180611_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='followup_customer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='followup_tech',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='location_add2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
