# Generated by Django 2.0.6 on 2018-06-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_auto_20180611_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='pre_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
