# Generated by Django 2.0.6 on 2018-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_partrequest_pre_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='pre_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='scheDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='sksid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='techEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='techName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='techNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='techPhone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tsq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='warrantyNote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
