# Generated by Django 2.0.6 on 2018-06-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_auto_20180613_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='sn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
