# Generated by Django 2.0.6 on 2018-06-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_partrequest_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='business_hour',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='location_add2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
