# Generated by Django 2.0.2 on 2018-06-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_auto_20180614_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='pre_diagnosis_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_add1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
