# Generated by Django 2.0.6 on 2018-06-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0026_auto_20180617_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequest',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
