# Generated by Django 2.0.6 on 2018-06-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_auto_20180618_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='techName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
