# Generated by Django 2.0.6 on 2018-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_auto_20180620_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
