# Generated by Django 2.0.2 on 2018-06-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0029_partrequest_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='pre_diagnosis_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitbasicinfo',
            name='timestamp_diagnosis',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
