# Generated by Django 2.0.6 on 2018-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0030_auto_20180621_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='pre_diagnosis',
            field=models.TextField(null=True),
        ),
    ]
