# Generated by Django 2.0.6 on 2018-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0031_auto_20180621_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequest',
            name='location_zip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='location_zip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
