# Generated by Django 2.0.2 on 2018-06-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0032_auto_20180625_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('model', models.ManyToManyField(to='request.UnitBasicInfo')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
