# Generated by Django 2.0.6 on 2018-06-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0033_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSimpleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sksid', models.CharField(blank=True, max_length=20, null=True)),
                ('file_field', models.FileField(upload_to='upload/%Y/%m/%d')),
            ],
        ),
        migrations.AlterModelOptions(
            name='partrequest',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
