# Generated by Django 2.0.6 on 2018-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0034_auto_20180629_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesimplemodel',
            name='file_field',
            field=models.FileField(upload_to='pppt/static/%Y/%m/%d/'),
        ),
    ]
