# Generated by Django 2.0.3 on 2018-07-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0035_auto_20180702_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='long_term_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filesimplemodel',
            name='file_field',
            field=models.FileField(upload_to='pppt/request/static/%Y/%m/%d/'),
        ),
    ]
