# Generated by Django 2.0.6 on 2018-07-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0036_auto_20180704_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequest',
            name='sn',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
