# Generated by Django 2.0.6 on 2018-07-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0037_auto_20180705_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitbasicinfo',
            options={'ordering': ('sksid',)},
        ),
    ]
