# Generated by Django 2.0.6 on 2018-07-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0038_auto_20180712_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequest',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
