# Generated by Django 2.0.6 on 2018-07-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0040_auto_20180713_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='inhouse',
            field=models.BooleanField(default=False),
        ),
    ]
