# Generated by Django 2.0.6 on 2018-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0041_unitbasicinfo_inhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='inhouse',
            field=models.BooleanField(choices=[(False, 'To 3rd party tech company'), (True, 'To in-house tech dispatcher')], default=False),
        ),
    ]
