# Generated by Django 2.0.6 on 2018-08-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0043_tech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partrequest',
            options={'ordering': ('sksid',)},
        ),
    ]
