# Generated by Django 2.0.6 on 2018-08-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('request', '0044_auto_20180801_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit'),
        ),
    ]
