# Generated by Django 2.0.6 on 2018-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0045_unitbasicinfo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_chn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
