# Generated by Django 2.0.3 on 2018-09-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0046_tag_name_chn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partrequest',
            options={'ordering': ('sksid',), 'permissions': (('change_part_status', 'Can change the status of part request'),)},
        ),
    ]
