# Generated by Django 2.0.6 on 2018-11-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0048_auto_20181011_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='part_type',
            field=models.IntegerField(blank=True, choices=[('NDA', 'NEXT DAY AIR'), ('2NDA', 'SECOND DAY AIR'), ('GROUND', 'GROUND')], default=2),
        ),
    ]
