# Generated by Django 2.0.6 on 2018-11-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0049_partrequest_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='after_market_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='part_type',
            field=models.IntegerField(blank=True, choices=[(1, 'PO'), (2, 'WARRANTY')], default=2),
        ),
    ]
