# Generated by Django 2.0.6 on 2018-11-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0050_auto_20181102_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partrequest',
            name='after_market_code',
        ),
        migrations.RemoveField(
            model_name='partrequest',
            name='weight',
        ),
    ]
