# Generated by Django 2.0.6 on 2018-11-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0051_auto_20181102_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.UnitBasicInfo'),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='pre_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
