# Generated by Django 2.0.6 on 2018-12-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0054_unitbasicinfo_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbasicinfo',
            name='replacement',
            field=models.BooleanField(default=False),
        ),
    ]
