# Generated by Django 2.0.6 on 2018-12-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0056_auto_20181219_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitbasicinfo',
            name='receiver',
        ),
    ]
