# Generated by Django 2.0.6 on 2018-12-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0057_remove_unitbasicinfo_receiver'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='unitbasicinfo',
        #     name='prefer_reached',
        #     field=models.CharField(max_length=90, null=True),
        # ),
    ]
