# Generated by Django 2.0.6 on 2018-12-29 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0058_unitbasicinfo_prefer_reached'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='unitbasicinfo',
        #     name='create_user',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AlterField(
            model_name='partrequest',
            name='location_add1',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='location_add2',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='address1',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='location_add1',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='location_add2',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_add1',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_add2',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
