# Generated by Django 2.0.6 on 2018-12-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0059_auto_20181228_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequest',
            name='location_add1',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='location_add2',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='address1',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='location_add1',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='location_add2',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_add1',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='unitbasicinfo',
            name='tech_add2',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
    ]
