# Generated by Django 2.0.6 on 2018-12-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0060_auto_20181228_2234'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='unitbasicinfo',
        #     name='prefer_reached',
        #     field=models.CharField(default='by phone', max_length=90),
        # ),
    ]
