# Generated by Django 2.0.6 on 2019-01-25 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20181224_1643'),
        ('request', '0062_auto_20181231_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Part'),
        ),
    ]
