# Generated by Django 2.0.6 on 2019-01-30 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0063_partrequest_part'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='unitbasicinfo',
        #     name='create_user',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='unitbasicinfo',
        #     name='prefer_reached',
        #     field=models.CharField(default='by phone', max_length=90),
        # ),
        migrations.AlterField(
            model_name='partrequest',
            name='sksid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
