# Generated by Django 2.0.6 on 2019-01-30 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0064_auto_20190130_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_creater', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddField(
        #     model_name='unitbasicinfo',
        #     name='create_user',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='unitbasicinfo',
        #     name='prefer_reached',
        #     field=models.CharField(default='by phone', max_length=90),
        # ),
    ]
