# Generated by Django 2.0.6 on 2018-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=20, null=True)),
                ('travel_t', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('labor_t', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('travel_c', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('labor_c', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('material_c', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_c', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sksid', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
