# Generated by Django 2.0.6 on 2018-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='labor_c',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='labor_t',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='material_c',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_c',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='travel_c',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='travel_t',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
