# Generated by Django 2.0.6 on 2018-06-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_invoice_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
