# Generated by Django 2.0.6 on 2018-07-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0037_auto_20180705_1711'),
        ('warranty', '0006_auto_20180705_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='incident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.UnitBasicInfo'),
        ),
    ]
