# Generated by Django 2.0.6 on 2018-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0007_invoice_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dispute_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Approved'), (2, 'Disputed')], default=0),
        ),
    ]
