# Generated by Django 2.0.6 on 2018-07-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0008_auto_20180712_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('add_time',)},
        ),
    ]
