# Generated by Django 2.0.6 on 2018-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0011_invoice_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=20)),
                ('branch_id', models.CharField(max_length=5)),
                ('customer_id', models.IntegerField()),
                ('bill2_name', models.CharField(max_length=100)),
                ('transaction', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('ship2_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('ship2_name', models.CharField(max_length=50)),
                ('ship2_address1', models.CharField(max_length=50)),
                ('ship2_address2', models.CharField(blank=True, max_length=50, null=True)),
                ('ship2_city', models.CharField(max_length=50)),
                ('ship2_state', models.CharField(max_length=50)),
                ('ship2_zip', models.CharField(max_length=50)),
            ],
        ),
    ]
