# Generated by Django 2.0.6 on 2018-09-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0012_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approved_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
