# Generated by Django 2.0.3 on 2018-09-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0013_invoice_approved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='need_w9',
            field=models.BooleanField(default=False),
        ),
    ]
