# Generated by Django 2.0.6 on 2018-11-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0014_invoice_need_w9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Approved'), (2, 'Disputed'), (3, 'In-house')], default=0),
        ),
    ]
