# Generated by Django 2.0.6 on 2019-02-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0016_auto_20190205_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('add_time',), 'permissions': (('approve_invoice', 'Can approve or dispute invoice'),)},
        ),
    ]
