# Generated by Django 2.0.6 on 2019-02-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0017_auto_20190207_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('add_time',), 'permissions': (('approve_invoice', 'Can approve or dispute invoice'), ('process_invoice', 'Can process invoice'))},
        ),
    ]
